# Physical parameters

offsets:
  shoulder_offset: 0.120 # measured from model
  elbow_offset: 0.027 # measured from model

inertia_parameters:
  base_mass: 2.0  # This mass might be incorrect
  shoulder_mass: 1.98
  upper_arm_mass: 3.4445
  forearm_mass: 1.437
  wrist_1_mass: 0.871
  wrist_2_mass: 0.805
  wrist_3_mass: 0.261

  shoulder_radius: 0.060   # manually measured
  upper_arm_radius: 0.054  # manually measured
  elbow_radius: 0.060      # manually measured
  forearm_radius: 0.040    # manually measured
  wrist_radius: 0.045      # manually measured

  links:
    base:
      radius: 0.075
      length: 0.038

  # model referring to https://www.universal-robots.com/articles/ur/application-installation/dh-parameters-for-calculations-of-kinematics-and-dynamics/
  center_of_mass:
    shoulder_cog:
      x: 0.0        # model.x
      y: 0.0        # -model.z
      z: -0.02      # model.y
    upper_arm_cog:
      x: -0.11355   # model.x - upper_arm_length
      y: 0.0        # model.y
      z: 0.1157     # model.z
    forearm_cog:
      x: -0.1632    # model.x - forearm_length
      y: 0.0        # model.y
      z: 0.0238     # model.z
    wrist_1_cog:
      x: 0.0        # model.x
      y: -0.01      # -model.z
      z: 0.0        # model.y
    wrist_2_cog:
      x: 0.0        # model.x
      y: 0.01       # model.z
      z: 0.0        # -model.y
    wrist_3_cog:
      x: 0.0        # model.x
      y: 0.0        # model.y
      z: -0.02      # model.z

  rotation:
    shoulder:
      roll: 1.570796326794897
      pitch: 0
      yaw: 0
    upper_arm:
      roll: 0
      pitch: 0
      yaw: 0
    forearm:
      roll: 0
      pitch: 0
      yaw: 0
    wrist_1:
      roll: 1.570796326794897
      pitch: 0
      yaw: 0
    wrist_2:
      roll: -1.570796326794897
      pitch: 0
      yaw: 0
    wrist_3:
      roll: 0
      pitch: 0
      yaw: 0

  tensor:
    shoulder:
      ixx: 0.002767
      ixy: 0.000010
      ixz: -0.000015
      iyy: 0.002150
      iyz: 0.000187
      izz: 0.002564
    upper_arm:
      ixx: 0.004268
      ixy: -0.000041
      ixz: -0.001508
      iyy: 0.046079
      iyz: -0.000013
      izz: 0.044943
    forearm:
      ixx: 0.001089
      ixy: 0
      ixz: -0.000009
      iyy: 0.011485
      iyz: 0.000002
      izz: 0.011204
    wrist_1:
      ixx: 0.001008
      ixy: -0.000001
      ixz: 0.000001
      iyy: 0.000822
      iyz: 0.000133
      izz: 0.000603
    wrist_2:
      ixx: 0.000641
      ixy: -0.000001
      ixz: 0.000002
      iyy: 0.000619
      iyz: -0.000026
      izz: 0.000386
    wrist_3:
      ixx: 0.000548
      ixy: 0.000002
      ixz: -0.000002
      iyy: 0.000274
      iyz: -0.000197
      izz: 0.000412
